In [70]:
import pandas as pd
from sklearn.cluster import AgglomerativeClustering,k_means
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from mlxtend.frequent_patterns import apriori, association_rules

import warnings
warnings.filterwarnings("ignore")

### Data collection

In [8]:
%pip install openpyxl

retail_data = pd.read_excel("Online Retail.xlsx", engine="openpyxl")
retail_data

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: openpyxl in c:\users\smanoharan\appdata\local\python\pythoncore-3.14-64\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\smanoharan\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

       InvoiceNo StockCode  ... CustomerID         Country
0         536365    85123A  ...    17850.0  United Kingdom
1         536365     71053  ...    17850.0  United Kingdom
2         536365    84406B  ...    17850.0  United Kingdom
3         536365    84029G  ...    17850.0  United Kingdom
4         536365    84029E  ...    17850.0  United Kingdom
...          ...       ...  ...        ...             ...
541904    581587     22613  ...    12680.0          France
541905    581587     22899  ...    12680.0          France
541906    581587     23254  ...    12680.0          France
541907    581587     23255  ...    12680.0          France
541908    581587     22138  ...    12680.0          France

[541909 rows x 8 columns]

### Data understanding

In [10]:
retail_data.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [14]:
retail_data.describe()

            Quantity                 InvoiceDate      UnitPrice     CustomerID
count  541909.000000                      541909  541909.000000  406829.000000
mean        9.552250  2011-07-04 13:34:57.156386       4.611114   15287.690570
min    -80995.000000         2010-12-01 08:26:00  -11062.060000   12346.000000
25%         1.000000         2011-03-28 11:34:00       1.250000   13953.000000
50%         3.000000         2011-07-19 17:17:00       2.080000   15152.000000
75%        10.000000         2011-10-19 11:27:00       4.130000   16791.000000
max     80995.000000         2011-12-09 12:50:00   38970.000000   18287.000000
std       218.081158                         NaN      96.759853    1713.600303

In [15]:
retail_data.drop_duplicates()

       InvoiceNo StockCode  ... CustomerID         Country
0         536365    85123A  ...    17850.0  United Kingdom
1         536365     71053  ...    17850.0  United Kingdom
2         536365    84406B  ...    17850.0  United Kingdom
3         536365    84029G  ...    17850.0  United Kingdom
4         536365    84029E  ...    17850.0  United Kingdom
...          ...       ...  ...        ...             ...
541904    581587     22613  ...    12680.0          France
541905    581587     22899  ...    12680.0          France
541906    581587     23254  ...    12680.0          France
541907    581587     23255  ...    12680.0          France
541908    581587     22138  ...    12680.0          France

[536641 rows x 8 columns]

In [16]:
retail_data.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [19]:
retail_data.drop(columns="CustomerID",inplace= True)

In [20]:
retail_data.isna().sum()

InvoiceNo         0
StockCode         0
Description    1454
Quantity          0
InvoiceDate       0
UnitPrice         0
Country           0
dtype: int64

In [22]:
retail_data.dropna(inplace=True)

In [24]:
retail_data.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
Country        0
dtype: int64

### Business Needs and understanding

In [27]:
retail_data["Country"].value_counts()

Country
United Kingdom          494024
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

In [32]:
Germany_data = retail_data[retail_data["Country"] == "Germany"]
Germany_data

       InvoiceNo StockCode  ... UnitPrice  Country
1109      536527     22809  ...      2.95  Germany
1110      536527     84347  ...      2.55  Germany
1111      536527     84945  ...      0.85  Germany
1112      536527     22242  ...      1.65  Germany
1113      536527     22244  ...      1.95  Germany
...          ...       ...  ...       ...      ...
541801    581578     22993  ...      1.25  Germany
541802    581578     22907  ...      0.85  Germany
541803    581578     22908  ...      0.85  Germany
541804    581578     23215  ...      2.08  Germany
541805    581578     22736  ...      1.65  Germany

[9495 rows x 7 columns]

In [42]:
Germany_data.groupby("Description")["Quantity"].sum().sort_values(ascending = False)

Description
ROUND SNACK BOXES SET OF4 WOODLAND     1218
ASSORTED COLOURS SILK FAN              1164
POSTAGE                                1104
WOODLAND CHARLOTTE BAG                 1019
PACK OF 72 RETROSPOT CAKE CASES        1002
                                       ...
TRIPLE PHOTO FRAME CORNICE               -2
GROW YOUR OWN PLANT IN A CAN             -3
BLUE PADDED SOFT MOBILE                  -3
SET OF 3 BABUSHKA STACKING TINS          -6
TRAVEL CARD WALLET KEEP CALM            -20
Name: Quantity, Length: 1703, dtype: int64

In [46]:
Germany_data.groupby("Description")[["Quantity","UnitPrice"]].sum().sort_values(by="Quantity", ascending=False)

                                     Quantity  UnitPrice
Description
ROUND SNACK BOXES SET OF4 WOODLAND       1218     353.20
ASSORTED COLOURS SILK FAN                1164       7.13
POSTAGE                                  1104    7843.00
WOODLAND CHARLOTTE BAG                   1019      50.02
PACK OF 72 RETROSPOT CAKE CASES          1002      21.45
...                                       ...        ...
TRIPLE PHOTO FRAME CORNICE                 -2       9.95
GROW YOUR OWN PLANT IN A CAN               -3       1.25
BLUE PADDED SOFT MOBILE                    -3       4.25
SET OF 3 BABUSHKA STACKING TINS            -6       8.50
TRAVEL CARD WALLET KEEP CALM              -20       0.84

[1703 rows x 2 columns]

### Data preprocessing

In [48]:
onehot = OneHotEncoder()

In [50]:
Germany_data.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
Country                   str
dtype: object

In [54]:
Germany_product_list = Germany_data['Description'].value_counts()

In [60]:
Germany_pivot_data= pd.pivot_table(data = Germany_data, values = 'Quantity', index =  'InvoiceNo',columns= "Description",aggfunc = sum).fillna(0)

In [ ]:
Germany_pivot_data = Germany_pivot_data.map(lambda x:0 if x==0 else 1)

In [63]:
Germany_pivot_data.describe()

Description   50'S CHRISTMAS GIFT BAG LARGE  ...  ZINC WILLIE WINKIE  CANDLE STICK
count                            603.000000  ...                        603.000000
mean                               0.008292  ...                          0.006633
std                                0.090757  ...                          0.081243
min                                0.000000  ...                          0.000000
25%                                0.000000  ...                          0.000000
50%                                0.000000  ...                          0.000000
75%                                0.000000  ...                          0.000000
max                                1.000000  ...                          1.000000

[8 rows x 1703 columns]

In [68]:
# Binary matrix is ready for association rules
# Convert to numpy array if needed
Germany_pivot_array =  Germany_pivot_data.values

In [93]:
apriori_value = apriori(Germany_pivot_data,min_support = 0.02,use_colnames=True)
apriori_value

      support                                           itemsets
0    0.029851            frozenset({3 HOOK HANGER MAGIC GARDEN})
1    0.033167    frozenset({3 PIECE SPACEBOY COOKIE CUTTER SET})
2    0.023217         frozenset({36 PENCILS TUBE RED RETROSPOT})
3    0.021559              frozenset({36 PENCILS TUBE WOODLAND})
4    0.029851     frozenset({5 HOOK HANGER RED MAGIC TOADSTOOL})
..        ...                                                ...
492  0.023217  frozenset({PLASTERS IN TIN SPACEBOY, ROUND SNA...
493  0.029851  frozenset({ROUND SNACK BOXES SET OF 4 FRUITS ,...
494  0.021559  frozenset({WOODLAND CHARLOTTE BAG, ROUND SNACK...
495  0.026534  frozenset({ROUND SNACK BOXES SET OF 4 FRUITS ,...
496  0.026534  frozenset({WOODLAND CHARLOTTE BAG, ROUND SNACK...

[497 rows x 2 columns]

In [97]:
association_rules(apriori_value, metric = "confidence",min_threshold = 0.8)

                                           antecedents  ... kulczynski
0                  frozenset({6 RIBBONS RUSTIC CHARM})  ...   0.474830
1              frozenset({ASSORTED COLOUR MINI CASES})  ...   0.455777
2           frozenset({BAKING SET 9 PIECE RETROSPOT })  ...   0.460892
3             frozenset({BIG DOUGHNUT FRIDGE MAGNETS})  ...   0.450305
4              frozenset({BISCUIT TIN 50'S CHRISTMAS})  ...   0.484943
..                                                 ...  ...        ...
183  frozenset({ROUND SNACK BOXES SET OF 4 FRUITS ,...  ...   0.537815
184  frozenset({ROUND SNACK BOXES SET OF 4 FRUITS ,...  ...   0.465332
185  frozenset({ROUND SNACK BOXES SET OF 4 FRUITS ,...  ...   0.498723
186  frozenset({WOODLAND CHARLOTTE BAG, ROUND SNACK...  ...   0.465332
187  frozenset({WOODLAND CHARLOTTE BAG, ROUND SNACK...  ...   0.488280

[188 rows x 14 columns]