In [4]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import AgglomerativeClustering,k_means
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
import scipy.cluster.hierarchy as sch
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

In [15]:
iris_data = load_iris()
iris_dataset = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
iris_dataset['target'] = iris_data.target

### Data collection

In [16]:
iris_dataset

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

### Data understanding

In [17]:
## as per the given data we need to create a cluster based on the features of the flowers input

In [18]:
iris_dataset.isna().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [19]:
iris_dataset.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

In [20]:
iris_dataset.dtypes

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
target                 int64
dtype: object

In [23]:
iris_dataset.drop_duplicates(inplace=True) ## --------------- 1 duplicate entries

### Business understanding

In [25]:
## the given data consists of 3 categories of flowers with different specs on it with 4 input features and the target is need to categories the correct specs with this three clusters 
## Iris setosa, Iris versicolor, and Iris virginica.

### Data preprossesing

In [31]:
input_data = iris_dataset.drop(columns=["target"])

In [33]:
y = iris_dataset["target"]

In [34]:
StandardScaler = StandardScaler()

In [36]:
scaled_X = pd.DataFrame(StandardScaler.fit_transform(input_data), columns=input_data.columns)

In [39]:
scaled_X.std().mean()

np.float64(1.0033726908565712)

In [45]:
cluster = k_means(input_data,n_clusters = 3)

In [50]:
cluster

(array([[5.006     , 3.428     , 1.462     , 0.246     ],
        [6.85384615, 3.07692308, 5.71538462, 2.05384615],
        [5.885     , 2.74166667, 4.37666667, 1.42666667]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1,
        1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1,
        1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2], dtype=int32),
 78.11184615384614)