In [ ]:
## BUSINESS understanding

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,precision_score,recall_score
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
import xgboost as xgb
from sklearn.preprocessing import StandardScaler
from matplotlib import pyplot as plt

In [2]:
pip install lightgbm

Requirement already satisfied: lightgbm in c:\users\smanoharan\appdata\local\python\pythoncore-3.14-64\lib\site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in c:\users\smanoharan\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from lightgbm) (2.4.3)
Requirement already satisfied: scipy in c:\users\smanoharan\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from lightgbm) (1.17.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import lightgbm as lgb

In [4]:
## data collection

In [5]:
credit_card_data = pd.read_csv('credit_card_clean.csv')
credit_card_data

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,1,20000.0,female,university,married,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,female,university,single,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,female,university,single,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,female,university,married,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,male,university,married,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000.0,male,highschool,married,39,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,29997,150000.0,male,highschool,single,43,-1,-1,-1,-1,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,29998,30000.0,male,university,single,37,4,3,2,-1,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,29999,80000.0,male,highschool,married,41,1,-1,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,30000,50000.0,male,university,married,46,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

In [ ]:
## Data understanding

In [6]:
credit_card_data.isnull().sum()

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_1        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
DEFAULT      0
dtype: int64

In [14]:
credit_card_data.dtypes

ID             int64
LIMIT_BAL    float64
SEX              str
EDUCATION        str
MARRIAGE         str
AGE            int64
PAY_1          int64
PAY_2          int64
PAY_3          int64
PAY_4          int64
PAY_5          int64
PAY_6          int64
BILL_AMT1    float64
BILL_AMT2    float64
BILL_AMT3    float64
BILL_AMT4    float64
BILL_AMT5    float64
BILL_AMT6    float64
PAY_AMT1     float64
PAY_AMT2     float64
PAY_AMT3     float64
PAY_AMT4     float64
PAY_AMT5     float64
PAY_AMT6     float64
DEFAULT        int64
dtype: object

In [7]:
credit_card_data.shape

(30000, 25)

In [17]:
## there is 30000 rows and 24 columns in the dataset. We need to predict the default payment next month which is the target variable. So we need to check the distribution of the target variable.
## there is 3 features which are object type and rest of the features are numerical. So we need to encode the categorical features before building the model.
## there is no null entries in the dataset. So we can directly move to the data preprocessing and model building.
## on data ID colums there is no use for model building. So we can drop that column from the dataset.

In [ ]:
## there is 30000 rows and 24 columns in the dataset. We need to predict the default payment next month which is the target variable. So we need to check the distribution of the target variable.

In [ ]:
## data preprocessing & preparing the data for model building

In [18]:
del credit_card_data['ID']

In [20]:
LE = LabelEncoder()

In [22]:
credit_card_data["SEX"] = LE.fit_transform(credit_card_data["SEX"])
credit_card_data["EDUCATION"] = LE.fit_transform(credit_card_data["EDUCATION"])
credit_card_data["MARRIAGE"] = LE.fit_transform(credit_card_data["MARRIAGE"])

In [23]:
credit_card_data

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,20000.0,0,3,0,24,2,2,-1,-1,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,0,3,2,26,-1,2,0,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,0,3,2,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,0,3,0,37,0,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,1,3,0,57,-1,0,-1,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,1,1,0,39,0,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,150000.0,1,1,2,43,-1,-1,-1,-1,0,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,30000.0,1,3,2,37,4,3,2,-1,0,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,80000.0,1,1,0,41,1,-1,0,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,50000.0,1,3,0,46,0,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

In [226]:
X = credit_card_data.drop(['DEFAULT'], axis=1)
X

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,20000.0,0,3,0,24,2,2,-1,-1,-2,...,689.0,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0
1,120000.0,0,3,2,26,-1,2,0,0,0,...,2682.0,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0
2,90000.0,0,3,2,34,0,0,0,0,0,...,13559.0,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0
3,50000.0,0,3,0,37,0,0,0,0,0,...,49291.0,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0
4,50000.0,1,3,0,57,-1,0,-1,0,0,...,35835.0,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,1,1,0,39,0,0,0,0,0,...,208365.0,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0
29996,150000.0,1,1,2,43,-1,-1,-1,-1,0,...,3502.0,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0
29997,30000.0,1,3,2,37,4,3,2,-1,0,...,2758.0,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0
29998,80000.0,1,1,0,41,1,-1,0,0,0,...,76304.0,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0
29999,50000.0,1,3,0,46,0,0,0,0,0,...,49764.0,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0

In [225]:
y = credit_card_data['DEFAULT']
y

0        1
1        1
2        0
3        0
4        0
        ..
29995    0
29996    0
29997    1
29998    1
29999    1
Name: DEFAULT, Length: 30000, dtype: int64

In [231]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=150,stratify=y,shuffle= True)

In [88]:
## model building

In [263]:
abm = AdaBoostClassifier(n_estimators = 50,learning_rate = 0.3)
gbm = GradientBoostingClassifier(n_estimators = 100,max_depth= 5,learning_rate = 0.3)
xgbm = xgb.XGBClassifier(n_estimators = 100,max_depth= 5,learning_rate = 0.3)
lgbm = lgb.LGBMClassifier(n_estimators = 100,max_depth= 5,learning_rate = 0.3)

In [219]:
## training the models

In [264]:
%%time
lgbm.fit(X_train, y_train,)

[LightGBM] [Info] Number of positive: 4645, number of negative: 16355
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003819 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3258
[LightGBM] [Info] Number of data points in the train set: 21000, number of used features: 23
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.221190 -> initscore=-1.258742
[LightGBM] [Info] Start training from score -1.258742
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
CPU times: total: 1.55 s
Wall time: 256 ms

LGBMClassifier(learning_rate=0.3, max_depth=5)

In [265]:
%%time
abm.fit(X_train, y_train)

CPU times: total: 1.53 s
Wall time: 1.64 s

AdaBoostClassifier(learning_rate=0.3)

In [266]:
%%time
gbm.fit(X_train, y_train)

CPU times: total: 10.2 s
Wall time: 10.6 s

GradientBoostingClassifier(learning_rate=0.3, max_depth=5)

In [267]:
%%time
xgbm.fit(X_train, y_train)

CPU times: total: 1.64 s
Wall time: 185 ms

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.3, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

In [268]:
y_pred_abm = abm.predict(X_train)
y_pred_gbm = gbm.predict(X_train)
y_pred_xgbm = xgbm.predict(X_train)
y_pred_lgbm = lgbm.predict(X_train)

In [45]:
## model testing

In [269]:
# use trained models to predict on test data
# do not refit on X_test/y_test, otherwise test evaluation is invalid

y_pred_abm_test = abm.predict(X_test)
y_pred_gbm_test = gbm.predict(X_test)
y_pred_xgbm_test = xgbm.predict(X_test)
y_pred_lgbm_test = lgbm.predict(X_test)

In [51]:
# model evaluation

In [ ]:
## training data evaluations for ada boosting

In [270]:
print("accuracy_score:", accuracy_score(y_train, y_pred_abm))
print("confusion_matrix:\n", confusion_matrix(y_train, y_pred_abm))
print("precision_score:", precision_score(y_train, y_pred_abm))
print("recall_score:", recall_score(y_train, y_pred_abm))

accuracy_score: 0.8177619047619048
confusion_matrix:
 [[15671   684]
 [ 3143  1502]]
precision_score: 0.687099725526075
recall_score: 0.3233584499461787

In [240]:
## training data evaluations for gradient boosting

In [271]:
print("accuracy_score:", accuracy_score(y_train, y_pred_gbm))
print("confusion_matrix:\n", confusion_matrix(y_train, y_pred_gbm))
print("precision_score:", precision_score(y_train, y_pred_gbm))
print("recall_score:", recall_score(y_train, y_pred_gbm))

accuracy_score: 0.8857619047619048
confusion_matrix:
 [[15966   389]
 [ 2010  2635]]
precision_score: 0.8713624338624338
recall_score: 0.5672766415500539

In [ ]:
## training data evaluations for extreame gradient boosting

In [272]:
print("accuracy_score:", accuracy_score(y_train, y_pred_xgbm))
print("confusion_matrix:\n", confusion_matrix(y_train, y_pred_xgbm))
print("precision_score:", precision_score(y_train, y_pred_xgbm))
print("recall_score:", recall_score(y_train, y_pred_xgbm))

accuracy_score: 0.87
confusion_matrix:
 [[15920   435]
 [ 2295  2350]]
precision_score: 0.8438061041292639
recall_score: 0.5059203444564048

In [ ]:
## training data evaluations for light gradient boosting

In [273]:
print("accuracy_score:", accuracy_score(y_train, y_pred_lgbm))
print("confusion_matrix:\n", confusion_matrix(y_train, y_pred_lgbm))
print("precision_score:", precision_score(y_train, y_pred_lgbm))
print("recall_score:", recall_score(y_train, y_pred_lgbm))

accuracy_score: 0.868904761904762
confusion_matrix:
 [[15882   473]
 [ 2280  2365]]
precision_score: 0.8333333333333334
recall_score: 0.5091496232508074

In [ ]:
## -----------> test data

In [ ]:
## test data evaluations for ada boosting

In [274]:
print("accuracy_score:", accuracy_score(y_test, y_pred_abm_test))
print("confusion_matrix:\n", confusion_matrix(y_test, y_pred_abm_test))
print("precision_score:", precision_score(y_test, y_pred_abm_test))
print("recall_score:", recall_score(y_test, y_pred_abm_test))

accuracy_score: 0.8137777777777778
confusion_matrix:
 [[6726  283]
 [1393  598]]
precision_score: 0.6787741203178207
recall_score: 0.30035158211953794

In [ ]:
## test data evaluations for gradient boosting

In [275]:
print("accuracy_score:", accuracy_score(y_test, y_pred_gbm_test))
print("confusion_matrix:\n", confusion_matrix(y_test, y_pred_gbm_test))
print("precision_score:", precision_score(y_test, y_pred_gbm_test))
print("recall_score:", recall_score(y_test, y_pred_gbm_test))

accuracy_score: 0.8072222222222222
confusion_matrix:
 [[6522  487]
 [1248  743]]
precision_score: 0.6040650406504066
recall_score: 0.37317930688096435

In [ ]:
## test data evaluations for extreame gradient boosting

In [276]:
print("accuracy_score:", accuracy_score(y_test, y_pred_xgbm_test))
print("confusion_matrix:\n", confusion_matrix(y_test, y_pred_xgbm_test))
print("precision_score:", precision_score(y_test, y_pred_xgbm_test))
print("recall_score:", recall_score(y_test, y_pred_xgbm_test))

accuracy_score: 0.8126666666666666
confusion_matrix:
 [[6609  400]
 [1286  705]]
precision_score: 0.6380090497737556
recall_score: 0.35409342039176295

In [ ]:
## test data evaluations for light gradient boosting

In [277]:
print("accuracy_score:", accuracy_score(y_test, y_pred_lgbm_test))
print("confusion_matrix:\n", confusion_matrix(y_test, y_pred_lgbm_test))
print("precision_score:", precision_score(y_test, y_pred_lgbm_test))
print("recall_score:", recall_score(y_test, y_pred_lgbm_test))

accuracy_score: 0.8098888888888889
confusion_matrix:
 [[6587  422]
 [1289  702]]
precision_score: 0.6245551601423488
recall_score: 0.35258663987945754

In [284]:
credit_card_data.columns

Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'DEFAULT'],
      dtype='str')

In [324]:
feature_importance = pd.DataFrame({
    'abm': abm.feature_importances_,
    'gbm': gbm.feature_importances_,
    'xgbm': xgbm.feature_importances_,
    'lgbm': lgbm.feature_importances_
}, index=X_train.columns)
feature_importance

                abm       gbm      xgbm  lgbm
LIMIT_BAL  0.099647  0.044431  0.024282   151
SEX        0.000000  0.003325  0.015508    22
EDUCATION  0.000000  0.006791  0.017376    29
MARRIAGE   0.000000  0.006359  0.016482    16
AGE        0.000000  0.033547  0.016286   173
PAY_1      0.323257  0.337623  0.424485    56
PAY_2      0.134828  0.062003  0.100670    19
PAY_3      0.097315  0.025990  0.067680    26
PAY_4      0.000000  0.010208  0.029835    23
PAY_5      0.020138  0.014051  0.034269    20
PAY_6      0.054757  0.016761  0.030960    38
BILL_AMT1  0.029951  0.059545  0.022210   148
BILL_AMT2  0.000000  0.032504  0.016835   119
BILL_AMT3  0.000000  0.035170  0.017730   117
BILL_AMT4  0.000000  0.033290  0.017991   123
BILL_AMT5  0.000000  0.025700  0.016776   114
BILL_AMT6  0.000000  0.034223  0.016948   116
PAY_AMT1   0.098810  0.041217  0.019165   179
PAY_AMT2   0.053558  0.039992  0.018586   169
PAY_AMT3   0.036732  0.047638  0.022222   164
PAY_AMT4   0.034630  0.032325  0.018580   151
PAY_AMT5   0.000000  0.026356  0.018107   150
PAY_AMT6   0.016377  0.030952  0.017018   152

In [ ]:
abm_top_features = feature_importance['abm']

In [300]:
abm_top_features.sort_index(ascending = True)

AGE          0.000000
BILL_AMT1    0.029951
BILL_AMT2    0.000000
BILL_AMT3    0.000000
BILL_AMT4    0.000000
BILL_AMT5    0.000000
BILL_AMT6    0.000000
EDUCATION    0.000000
LIMIT_BAL    0.099647
MARRIAGE     0.000000
PAY_1        0.323257
PAY_2        0.134828
PAY_3        0.097315
PAY_4        0.000000
PAY_5        0.020138
PAY_6        0.054757
PAY_AMT1     0.098810
PAY_AMT2     0.053558
PAY_AMT3     0.036732
PAY_AMT4     0.034630
PAY_AMT5     0.000000
PAY_AMT6     0.016377
SEX          0.000000
Name: abm, dtype: float64

In [294]:
abm_top_features.head(10)

AGE          0.000000
BILL_AMT1    0.029951
BILL_AMT2    0.000000
BILL_AMT3    0.000000
BILL_AMT4    0.000000
BILL_AMT5    0.000000
BILL_AMT6    0.000000
EDUCATION    0.000000
LIMIT_BAL    0.099647
MARRIAGE     0.000000
Name: abm, dtype: float64

In [303]:
import seaborn as sns

In [ ]:
sns.barplot(abm_top_features.sort_index(ascending = True),x= ,y = abm)

NameError: name 'index' is not defined